# Generated by Django 4.2.7 on 2023-11-28 04:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_updated', models.DateTimeField(auto_now=True)),
                ('date_deadline', models.DateField()),
                ('time_deadline', models.TimeField()),
                ('status', models.BooleanField(default=False)),
                ('hints', models.TextField(blank=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='task.category')),
                ('user_Constructive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks_Constructive', to=settings.AUTH_USER_MODEL)),
                ('user_doing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks_doing', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
