# Generated by Django 4.2.7 on 2023-11-26 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_task_hints_alter_task_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='slug',
            field=models.SlugField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
