# Generated by Django 4.2.7 on 2023-11-26 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_task_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='slug',
        ),
    ]
